"""initial_schema

Revision ID: 5840d1bf63bc
Revises: 
Create Date: 2026-05-10 16:13:03.660459

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '5840d1bf63bc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Enum('queued', 'crawling', 'scanning', 'completed', 'failed', 'cancelled', name='scanstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_urls_found', sa.Integer(), nullable=False),
    sa.Column('total_findings', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('vuln_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='severity'), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=False),
    sa.Column('cvss_vector', sa.String(length=256), nullable=True),
    sa.Column('owasp_category', sa.String(length=8), nullable=True),
    sa.Column('owasp_name', sa.String(length=128), nullable=True),
    sa.Column('affected_url', sa.String(length=2048), nullable=False),
    sa.Column('affected_parameter', sa.String(length=256), nullable=True),
    sa.Column('payload_used', sa.Text(), nullable=True),
    sa.Column('evidence_request', sa.Text(), nullable=True),
    sa.Column('evidence_response', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Enum('confirmed', 'tentative', name='confidence'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_owasp_category'), 'findings', ['owasp_category'], unique=False)
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_vuln_type'), 'findings', ['vuln_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_vuln_type'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_owasp_category'), table_name='findings')
    op.drop_table('findings')
    op.drop_table('scans')
    # ### end Alembic commands ###
